/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_neoqee_jnidemo_JniUtil */

#ifndef _Included_com_neoqee_jnidemo_JniUtil
#define _Included_com_neoqee_jnidemo_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_neoqee_jnidemo_JniUtil
 * Method:    printStringByJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_neoqee_jnidemo_JniUtil_printStringByJni
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
